### ISSUE TITLE
レスポンシブ・環境チェック

### ISSUE THREAD

**Issue by REDnjgngim** [REDnjgngim/campbbs#10]
チェック内容
- スレッドの表示
- 投稿フォーム4種開く
- 新規投稿出来る
- フィルタがかけられる
- 画像が表示できる
- [x] PC・16/9・FHD
- [x] PC・16/9・4K
- [x] PC・1/1・FHD
- [x] PC・9/16より縦に細長い
- [x] PC・16/9より横に細長い
- [x] スマホ・縦
- [x] スマホ・横
- [x] スマホ・縦横切替
- [x] タブレットの縦横(ブラウザのシミュレーターで確認)
- [x] 細長いスマホの縦横(ブラウザのシミュレーターで確認)
- [x] PC・chrome
- [x] PC・firefox
- [x] PC・Edge
- [x] PC・safari (誰かやって)
- [x] Android・chrome
- [x] iOS・safari (誰かやって)

**Comment by patatan168** [comment]
`display:grid`を使用を要検討すること
https://nnc-studio.jp/plugin/2023/12/26/display-grid/
