### ISSUE TITLE
まだやってない細かい処理メモ

### ISSUE THREAD

**Issue by REDnjgngim** [REDnjgngim/campbbs#30]
- [x] サーバーのエラー処理をもう少し細かく入れる #33
- [x] メッセージの削除時に画像も消す
- [x] 島idを持って認証を取っているので、サーバーから渡す値からパスワードを抜く
- [x] 英文字だけだとタイトルと投稿者名がはみ出る対応する
- [x] logとtimelineのファイルの中身が空でも動くようにしたい
- [x] 1桁のときの日付の0埋めする
- [x] 名前の入力文字数設定する
- [x] タイトルの入力文字数設定する
- [x] 本文の入力文字数設定する
- [x] 本文に改行が入らない
- [x] スレッドのインデント上限いれる
- [x] MordalWindowの構成をリファクタする
- [x] グループの変数をスレッドに変える
- [x] ある程度レンダリングの回数を減らす。特にform系
- [x] 相手の書き込みがない時に外交文書送るとタイムラインがなくて表示されない
- [x] 外交文書、自陣営のメッセージだけ表示するフィルタを入れたい
- [x] 分割読み込みで固定メッセージが常に一番上に表示されなくなったので直す
- [x] 画像を付けて投稿するとget→postの順でメッセージが送れてないように見えるので直す
~~リロード時とポスト時は全部更新するので、最終閲覧自国も更新したい~~→1ファイルへの読み書き量がかなり多くなりそうなので無し

**Comment by REDnjgngim** [comment]
- [ ] 箱庭の自動リセット時に中身もきれいにしたい
- [ ] 箱庭諸島から遷移したときのリファラ周りの認証設定
- [ ] スマホ横画面だと投稿フォームが狭すぎるのを解消する

**Comment by REDnjgngim** [comment]
cookieをすっかり忘れてたので入れたい。文字色と名前。
(箱庭番号と開催番号で分けて保存しないと潜伏がバレる可能性があり。期限は1ヶ月もあれば十分)

**Comment by patatan168** [comment]
cookieの処理はperl側で行うのが安全。
恐らくSameSite Luxがデフォルトなのでデバッグ環境では上手く動かなくてハマる可能性あり。
https://qiita.com/KWS_0901/items/695bd1ecc17a8c2e6d69
SameSiteをデバッグ環境ではnoneにしておくのが楽。

**Comment by REDnjgngim** [comment]
perl側だとなんか一筋縄じゃ実装できなさそうなのと、今回はセッションみたいなのじゃなくてフォームの下書き保存の延長線みたいなものなので、React側で実装しようかなと思います。
