### ISSUE TITLE
通信処理時のトースト周り整備

### ISSUE THREAD

**Issue by REDnjgngim** [REDnjgngim/campbbs#4]
トーストの実装が完全じゃないのでやる
- [x] isSuccessとかでトーストの文言や色を変える
- [ ] ~~最初のログリロード時のトーストは出さないようにする~~→通信自体はしてるので出す

**Comment by patatan168** [comment]
https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values

ここが参考になるかも
